### ISSUE TITLE
Uncaught node.js Error

### ISSUE THREAD

**Issue by abdullahoguk** [szwacz/sputnik#23]
![Uncaught node.js Error](http://i.imgur.com/400q2LS.png)
```
Uncaught node.js Error 

RangeError: index out of range
    at checkOffset (buffer.js:425:11)
    at Buffer.readUInt16BE (buffer.js:461:5)
    at eval (/opt/Sputnik/helpers/feedsWaitingRoom.js:32:38)
    at eval (fs.js:258:14)
    at Object.eval [as oncomplete] (fs.js:97:15)
```

**Comment by szwacz** [comment]
Does it happen all the time, or happened only once?

**Comment by abdullahoguk** [comment]
It happened after adding an RSS feed. (I could not rememer which one)  I haven't accessed program since.
Also I couldn't uninstalled to re-install.

**Comment by abdullahoguk** [comment]
I deleted everything in `~/.config/Sputnik/userdata/feeds-waiting-room` then solved.

**Comment by szwacz** [comment]
I was hoping for that solution :)
New version of sputnik (if I will be able to deliver it someday) doesn't have feeds-waiting-room at all.
