### ISSUE TITLE
App start err

### ISSUE THREAD

**Issue by bbilginn** [szwacz/sputnik#26]
You can only give you an idea about this errors? How to generate these files to source folder?
This is my first attempt :sweat:

![image](https://cloud.githubusercontent.com/assets/2061337/15908434/5e8a4362-2dca-11e6-9e52-89993594c2d7.png)

**Comment by szwacz** [comment]
The code in master is not in workable state. I've started to rewriting the app and never finished it. It wont' work. Sorry :)
